Skip test_abi on hosts without abidiff
The test code has been slightly changed to allow it being skipped in the absence
of abidiff, and the configure.ac check is not needed anymore.

Signed-off-by: Matheus Castanho <msc@linux.ibm.com>

diff --git a/test/test_abi b/test/test_abi
--- a/test/test_abi
+++ b/test/test_abi
@@ -4,17 +4,27 @@
 #   1. Make sure that libnxz provides all zlib symbols
 #   2. Guarantee that new symbols are not added/removed by mistake
 
-# Exit on first failure
-set -e
-
 # These should be either the .so files or their descriptions generated by abidw
 zlib_abi_orig="${srcdir:+${srcdir}/}libz.abi"
 libnxz_abi="${srcdir:+${srcdir}/}libnxz.abi"
-libnxz="../lib/.libs/libnxz.so"
+libnxz="$1"
 zlib_supp="${srcdir:+${srcdir}/}zlib.supp"
 
-if [ -z "${libnxz}" ] || [ ! -f "${libnxz}" ]; then
-    echo "Usage: $0 /path/to/libnxz.so"
+which abidiff &> /dev/null
+if [ $? -ne 0 ]; then
+    echo "No abidiff binary found, skipping..."
+    exit 77
+fi
+
+# Exit on first failure
+set -e
+
+if [ -z "${libnxz}" ]; then
+    libnxz="../lib/.libs/libnxz.so"
+fi
+
+if [ ! -f "${libnxz}" ]; then
+    echo "Couldn't find file: ${libnxz}"
     exit 1
 fi
 
